"""SummaryAgent — verdict math (deterministic) + prose generation (LLM).

The rollup numbers are produced in code so they're testable; only the
exec-summary prose is generated by the LLM.
"""
from __future__ import annotations

from typing import Sequence

from .schemas import (CapabilityMatch, ComplianceItem,
                       EligibilityCheck, Risk)


def compute_rollup(
    matches: Sequence[CapabilityMatch],
    compliance: Sequence[ComplianceItem],
    *,
    thresholds: dict,
    mandatory_penalty: float,
    analytics_boost: float,
) -> dict:
    if not matches:
        fit = 0.0
    else:
        fit = sum(m.match_score for m in matches) / len(matches)
    failed_mandatory = any(c.mandatory and c.status == "fail" for c in compliance)
    penalty = mandatory_penalty if failed_mandatory else 0.0
    win = max(0.0, min(1.0, fit * (1.0 - penalty) * (1.0 + analytics_boost)))
    if fit >= thresholds["bid_min_fit"]:
        verdict = "bid"
    elif fit <= thresholds["no_bid_max_fit"]:
        verdict = "no_bid"
    else:
        verdict = "review"
    return {"fit_score": round(fit, 4), "win_probability": round(win, 4),
            "verdict": verdict}


async def generate_summary_prose(
    *,
    rollup: dict,
    compliance: Sequence[ComplianceItem],
    eligibility: Sequence[EligibilityCheck],
    risks: Sequence[Risk],
    llm_client,
) -> str:
    """LLM-generated 1-page summary. Falls back to a bullet list when the
    LLM client is None (test path)."""
    bullets = [
        f"**AI verdict:** {rollup['verdict'].upper()}",
        f"**Fit score:** {rollup['fit_score']:.0%}",
        f"**Win probability:** {rollup['win_probability']:.0%}",
    ]
    failed = [c.label for c in compliance if c.status == "fail" and c.mandatory]
    if failed:
        bullets.append("**Mandatory fails:** " + ", ".join(failed))
    high_risk = [r.title for r in risks if r.severity == "high"]
    if high_risk:
        bullets.append("**High-severity risks:** " + ", ".join(high_risk))
    skeleton = "\n".join(f"- {b}" for b in bullets)
    if llm_client is None:
        return skeleton
    prompt = (
        "Write a 4-paragraph executive summary for a bid committee. "
        "Open with the verdict and reasoning, then cover compliance coverage, "
        "key risks, and an explicit recommendation including any conditions for "
        "proceeding. Stay factual and reference the bullet list below; do not "
        "invent.\n\n" + skeleton + "\n"
    )
    try:
        result = await llm_client.generate(prompt, [])
        return getattr(result, "text", None) or skeleton
    except Exception:
        return skeleton
